language: android
sudo: required

jdk:
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - ANDROID_API_LEVEL=25
    - EMULATOR_API_LEVEL=24
    - ANDROID_ABI=armeabi-v7a
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=20

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.3
    - build-tools-24.0.3
    - android-${ANDROID_API_LEVEL}
    - android-${EMULATOR_API_LEVEL}
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-google_apis-${ANDROID_API_LEVEL}
    - sys-img-${ANDROID_ABI}-google_apis-${EMULATOR_API_LEVEL}

before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME

before_script:
  - echo no | android create avd --force -n test -t android-${EMULATOR_API_LEVEL} --abi $ANDROID_ABI --tag google_apis
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build connectedCheck jacocoTestReportDebug coveralls
